spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev-db-server:3306/mingodb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dev_user
    password: dev_password

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

    properties:
      hibernate:
        format_sql: true
        highlight_sql: false
        use_sql_comments: true

    open-in-view: false

decorator:
  datasource:
    enabled: true
    datasource-proxy:
      query:
        enable-logging: true
        log-level: info


api:
  test-client:
    url: aaa
    connection-timeout: 1s
    read-timeout: 10s
    api-key: bbb

logging:
  level:
    mingovvv: DEBUG # 개발 서버까지는 디버그 로그 확인
    org.hibernate.SQL: INFO
