spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mingodb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true # 외부 접속 허용 (필요시)

  jpa:
    hibernate:
      ddl-auto: validate # 변경금지

    show-sql: false # datasource-proxy 사용

    properties:
      hibernate:
        format_sql: true  # 쿼리 예쁘게 줄바꿈
        highlight_sql: false # datasource-proxy 사용
        use_sql_comments: true # 쿼리 옆에 주석 달기

    open-in-view: false # 변경금지

  jackson:
    serialization:
      indent_output: true

decorator:
  datasource:
    enabled: true
    datasource-proxy:
      query:
        enable-logging: true
        log-level: info

api:
  test-client:
    url: aaa
    connection-timeout: 1s
    read-timeout: 10s
    api-key: bbb

logging:
  level:
    mingovvv: DEBUG
